In [122]:
import pandas as pd
import numpy as np
import random

In [123]:
ArExponent_min, ArExponent_max = 1, 100
FExponent_min, FExponent_max = 1,100

Arflux1_min, Arflux1_max = 0.0001, 0.01
Arflux2_min, Arflux2_max = 0.0001, 0.01
Arflux3_min, Arflux3_max = 0.0001, 0.01
Arflux4_min, Arflux4_max = 0.0001, 0.01
Arflux5_min, Arflux5_max = 0.0001, 0.01
Arflux6_min, Arflux6_max = 0.0001, 0.01

Fflux1_min, Fflux1_max = 0.0001, 0.01
Fflux2_min, Fflux2_max = 0.0001, 0.01
Fflux3_min, Fflux3_max = 0.0001, 0.01
Fflux4_min, Fflux4_max = 0.0001, 0.01
Fflux5_min, Fflux5_max = 0.0001, 0.01
Fflux6_min, Fflux6_max = 0.0001, 0.01

yield_at_zero1_min, yield_at_zero1_max = 1,5
yield_at_zero2_min, yield_at_zero2_max = 1,5
yield_at_zero3_min, yield_at_zero3_max = 1,5

theta_max1_min, theta_max1_max = 30,100
theta_max2_min, theta_max1_max = 30,100
theta_max3_min, theta_max1_max = 30,100

mizk_min, mizk_max = 0.001,0.005

p1_min, p1_max = 0, 0.002
p2_min, p2_max = 0.8, 1
p3_min, p3_max = 0, 0.002
p4_min, p4_max = 0.5,0.9
p5_min, p5_max = 0, 0.0002

In [124]:
features = ['Arflux1','Arflux2','Arflux3','Arflux4','Arflux5','Arflux6',
            'Fflux1','Fflux2','Fflux3','Fflux4','Fflux5','Fflux6',
            'ArExponent','FrExponent',
            'yield_at_zero1','yield_at_zero2','yield_at_zero3',
            'yield_max1','yield_max2','yield_max3',
            'theta_max1','theta_max2','theta_max3','mizk',
            'p1','p2','p3','p4','p5']

In [125]:
feature_range_values = [[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],
                        [0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],[0.0001,0.01],
                        [1,100],[1,100],
                        [1,5],[1,5],[1,5],
                        [1,10],[1,10],[1,10],
                        [30,90],[30,90],[30,90],[0.001,0.005],
                        [0, 0.002],[0.8, 1],[0, 0.002],[0.5,0.9],[0, 0.0002]]

In [126]:
features_ranges = {}
for i in range(len(features)):
    features_ranges[features[i]] = feature_range_values[i]

In [127]:
features_ranges

{'Arflux1': [0.0001, 0.01],
 'Arflux2': [0.0001, 0.01],
 'Arflux3': [0.0001, 0.01],
 'Arflux4': [0.0001, 0.01],
 'Arflux5': [0.0001, 0.01],
 'Arflux6': [0.0001, 0.01],
 'Fflux1': [0.0001, 0.01],
 'Fflux2': [0.0001, 0.01],
 'Fflux3': [0.0001, 0.01],
 'Fflux4': [0.0001, 0.01],
 'Fflux5': [0.0001, 0.01],
 'Fflux6': [0.0001, 0.01],
 'ArExponent': [1, 100],
 'FrExponent': [1, 100],
 'yield_at_zero1': [1, 5],
 'yield_at_zero2': [1, 5],
 'yield_at_zero3': [1, 5],
 'yield_max1': [1, 10],
 'yield_max2': [1, 10],
 'yield_max3': [1, 10],
 'theta_max1': [30, 90],
 'theta_max2': [30, 90],
 'theta_max3': [30, 90],
 'mizk': [0.001, 0.005],
 'p1': [0, 0.002],
 'p2': [0.8, 1],
 'p3': [0, 0.002],
 'p4': [0.5, 0.9],
 'p5': [0, 0.0002]}

In [128]:
num_samples = 10
number_of_features = len(features)

In [129]:
number_of_features

29

In [130]:
X = np.empty((num_samples,number_of_features))
for i in range(num_samples):
    for j in range(number_of_features):
        X[i][j] = round(random.uniform(feature_range_values[j][0], feature_range_values[j][1]),4)

In [131]:
for i in range(len(X)):
    if (X[i][17] < X[i][14]):
        while (X[i][17] < X[i][14]):
            X[i][17] = round(random.uniform(feature_range_values[17][0], feature_range_values[17][1]),4)
    if (X[i][18] < X[i][15]):
        while (X[i][18] < X[i][15]):
            X[i][18] = round(random.uniform(feature_range_values[18][0], feature_range_values[18][1]),4)
    if (X[i][19] < X[i][16]):
        while (X[i][19] < X[i][16]):
            X[i][19] = round(random.uniform(feature_range_values[19][0], feature_range_values[19][1]),4)

In [132]:
X_dataframe = pd.DataFrame(X,columns = features)

In [133]:
X_dataframe

,Arflux1,Arflux2,Arflux3,Arflux4,Arflux5,Arflux6,Fflux1,Fflux2,Fflux3,Fflux4,...,yield_max3,theta_max1,theta_max2,theta_max3,mizk,p1,p2,p3,p4,p5
0,0.0035,0.0084,0.0032,0.0005,0.0058,0.0100,0.0006,0.0021,0.0060,0.0015,...,9.9589,36.1016,54.2790,31.2782,0.0040,0.0012,0.9498,0.0015,0.6240,0.0000
1,0.0078,0.0005,0.0074,0.0046,0.0001,0.0062,0.0070,0.0023,0.0069,0.0066,...,5.8074,49.5991,75.4226,73.5876,0.0026,0.0000,0.8782,0.0002,0.6669,0.0001
2,0.0062,0.0019,0.0070,0.0011,0.0004,0.0024,0.0093,0.0077,0.0037,0.0093,...,7.1926,62.9968,66.6365,85.3758,0.0038,0.0017,0.8335,0.0001,0.5848,0.0002
3,0.0063,0.0037,0.0007,0.0060,0.0100,0.0078,0.0022,0.0028,0.0099,0.0041,...,7.4400,67.6200,60.2955,57.9501,0.0031,0.0003,0.8356,0.0016,0.7247,0.0000
4,0.0091,0.0025,0.0095,0.0057,0.0034,0.0010,0.0050,0.0021,0.0031,0.0011,...,4.4918,87.8015,32.3745,69.2940,0.0041,0.0003,0.9566,0.0000,0.7391,0.0001
5,0.0019,0.0069,0.0056,0.0016,0.0028,0.0064,0.0069,0.0052,0.0024,0.0086,...,8.9632,51.2018,53.0544,81.3196,0.0026,0.0015,0.9699,0.0019,0.7683,0.0001
6,0.0088,0.0063,0.0038,0.0045,0.0060,0.0075,0.0023,0.0004,0.0063,0.0007,...,8.1736,58.3644,43.9759,52.9057,0.0028,0.0004,0.9429,0.0017,0.6287,0.0001
7,0.0042,0.0085,0.0080,0.0051,0.0023,0.0047,0.0061,0.0044,0.0099,0.0032,...,3.6224,70.8423,41.7315,72.0669,0.0036,0.0018,0.8436,0.0011,0.8278,0.0002
8,0.0083,0.0067,0.0052,0.0009,0.0065,0.0033,0.0095,0.0038,0.0075,0.0068,...,6.4166,51.4368,72.8940,42.9664,0.0033,0.0018,0.8963,0.0004,0.8656,0.0001
9,0.0003,0.0061,0.0027,0.0038,0.0031,0.0086,0.0040,0.0044,0.0007,0.0043,...,9.7312,85.9453,78.5656,75.7698,0.0035,0.0019,0.9970,0.0010,0.7560,0.0002

In [134]:
sed = "sed  -e 's/Arflux1/'$Arflux1'/g' -e 's/Arflux2/'$Arflux2'/g' -e 's/Arflux3/'$Arflux3'/g' -e 's/Arflux4/'$Arflux4'/g' -e 's/Arflux5/'$Arflux5'/g' -e 's/Arflux6/'$Arflux6'/g' -e 's/Fflux1/'$Fflux1'/g' -e 's/Fflux2/'$Fflux2'/g' -e 's/Fflux3/'$Fflux3'/g' -e 's/Fflux4/'$Fflux4'/g' -e 's/Fflux5/'$Fflux5'/g' -e 's/Fflux6/'$Fflux6'/g' -e 's/ArExponent/'$ArExponent'/g' -e 's/FrExponent/'$FrExponent'/g' -e 's/yield_at_zero1/'$yield_at_zero1'/g' -e 's/yield_max1/'$yield_max1'/g' -e 's/theta_max1/'$theta_max1'/g' -e 's/yield_at_zero2/'$yield_at_zero2'/g' -e 's/yield_max2/'$yield_max2'/g' -e 's/theta_max2/'$theta_max2'/g' -e 's/yield_at_zero3/'$yield_at_zero3'/g' -e 's/yield_max3/'$yield_max3'/g' -e 's/theta_max3/'$theta_max3'/g' -e 's/mizk/'$mizk'/g' -e 's/p1/'$p1'/g' -e 's/p2/'$p2'/g' -e 's/p3/'$p3'/g' -e 's/p4/'$p4'/g' -e 's/p5/'$p5'/g' -e 's/etch_time/'$etch_time'/g' etching.cmd > temp_etching.cmd\n"
sed2 = "sed  -e 's/Arflux1/'$Arflux1'/g' -e 's/Arflux2/'$Arflux2'/g' -e 's/Arflux3/'$Arflux3'/g' -e 's/Arflux4/'$Arflux4'/g' -e 's/Arflux5/'$Arflux5'/g' -e 's/Arflux6/'$Arflux6'/g' -e 's/Fflux1/'$Fflux1'/g' -e 's/Fflux2/'$Fflux2'/g' -e 's/Fflux3/'$Fflux3'/g' -e 's/Fflux4/'$Fflux4'/g' -e 's/Fflux5/'$Fflux5'/g' -e 's/Fflux6/'$Fflux6'/g' -e 's/ArExponent/'$ArExponent'/g' -e 's/FrExponent/'$FrExponent'/g' -e 's/yield_at_zero1/'$yield_at_zero1'/g' -e 's/yield_max1/'$yield_max1'/g' -e 's/theta_max1/'$theta_max1'/g' -e 's/yield_at_zero2/'$yield_at_zero2'/g' -e 's/yield_max2/'$yield_max2'/g' -e 's/theta_max2/'$theta_max2'/g' -e 's/yield_at_zero3/'$yield_at_zero3'/g' -e 's/yield_max3/'$yield_max3'/g' -e 's/theta_max3/'$theta_max3'/g' -e 's/mizk/'$mizk'/g' -e 's/p1/'$p1'/g' -e 's/p2/'$p2'/g' -e 's/p3/'$p3'/g' -e 's/p4/'$p4'/g' -e 's/p5/'$p5'/g' -e 's/etch_time/'$etch_time'/g' etching_data_extraction.cmd > temp_etching_data_extraction.cmd\n"

In [135]:
file_name = ''
for feature in features:
    file_name+=f"_{feature}"

In [136]:
file_name

'_Arflux1_Arflux2_Arflux3_Arflux4_Arflux5_Arflux6_Fflux1_Fflux2_Fflux3_Fflux4_Fflux5_Fflux6_ArExponent_FrExponent_yield_at_zero1_yield_at_zero2_yield_at_zero3_yield_max1_yield_max2_yield_max3_theta_max1_theta_max2_theta_max3_mizk_p1_p2_p3_p4_p5'

In [137]:
run_files = 'stopo temp_etching.cmd\nstopo temp_etching_data_extraction.cmd\n'

In [138]:
text  = ''

for i in range(len(X)):
    
    params = ''
    dir_name = ''
    for j in range(len(X[0])):
        params += f'{features[j]}={X[i][j]}\n'
        dir_name += f'_{X[i][j]}'
    text+= f'mkdir -p csvfiles/file{dir_name}\n'
    for k in range(6):
        text+= 'export '
        text += params
        text += f"etch_time={2*(k+1)}\n"
        text += sed
        text += sed2
        text += run_files

In [139]:
with open('exec.sh','w') as file:
    file.write(text)